# Generated by Django 5.0.7 on 2024-07-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="comment",
            field=models.CharField(default="Not Available", max_length=40),
        ),
    ]
